
  CREATE TABLE "DEPENDENTE" 
   (	"NOMDEP" CHAR(30), 
	"DATNASC" DATE, 
	"MATEMP" NUMBER(*,0), 
	 CONSTRAINT "PK_DEP" PRIMARY KEY ("MATEMP", "NOMDEP")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "DEPENDENTE" ADD CONSTRAINT "FK_EMP_DEP" FOREIGN KEY ("MATEMP")
	  REFERENCES "EMPREGADO" ("MATEMP") ENABLE;