
  CREATE TABLE "EMPREGADO" 
   (	"MATEMP" NUMBER(*,0) NOT NULL ENABLE, 
	"NOMEMP" CHAR(30) NOT NULL ENABLE, 
	"ENDEMP" CHAR(80), 
	"CIDEMP" CHAR(20), 
	 CONSTRAINT "PK_EMP" PRIMARY KEY ("MATEMP")
  USING INDEX  ENABLE
   ) ;